---
- name: Update and Upgrade Ubuntu Systems
  hosts: all
  become: true
  tasks:
    - name: Update apt repo and cache (apt update)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Upgrade all packages (apt full-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        dpkg_options: 'force-confdef,force-confold'
        autoremove: yes
        autoclean: yes
      register: apt_action

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server (if required)
      ansible.builtin.reboot:
        msg: "Rebooting due to system updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required_file.stat.exists